### PR TITLE
BS-95 Replaced thin Boost with ASIO standalone

### PR DESCRIPTION
**Pull request by kevinfields-youitv**
- WebsocketPP doesn't need anything more than ASIO standalone.

### CODE REVIEW

**Comment by Halmo** [comment]
As far as upgrading goes in the future would it be better to leave boost and just have it as a configurable option? (So that there is less of an impact on the repo)

**Comment by kevinfields-youitv** [comment]
The issue with leaving boost is that it causes build failures for the Cloud team. WebsocketPP doesn't require boost itself, but only ASIO.

**Comment by Halmo** [comment]
I see, but there's no way to leave it in the repo and have hunter only install the ASIO and not boost?

**Comment by kevinfields-youitv** [comment]
No. The standalone version of ASIO is not available through Hunter.

**Review by patrickyoui — APPROVED** [review]
Looks good to me...

**Pull request merged**
